
var spring = {
    middle_o: {
        Chinese: [
            {subject: "专题一：标题的含义和作用",subjectCombine:"", content: "《爸爸的花儿落了》课文内容理解、标题的含义和作用", hour: 2, combine:9999, reading: "本阶段课程计划安排40课时，课程内容紧扣初一下册重难点，从教材出发明确单元重点，同时在此基础上进行延伸拓展，侧重知识点及答题方法和技巧的梳理。建议学生在学习过程中如有问题及时提出，具体教学可根据学生掌握情况适当调整。",},
            {subject: "专题二： 现代诗歌理解",subjectCombine:"", content: "《诗两首》、诗歌的主题、象征的含义", hour: 2, combine:"", reading: "",},
            {subject: "专题三： 文言文巩固1",subjectCombine:"", content: "《伤仲永》重点实词虚词解释、人物分析、课文主旨", hour: 2, combine:"", reading: "",},
            {subject: "专题四：写作和口语交际",subjectCombine:"", content: "写作作文方法指导：叙事要完整", hour: 2, combine:"", reading: "",},
            {subject: "专题五： 揣摩精彩词句段落",subjectCombine:"", content: "《黄河颂》课文内容理解、修辞方法的作用", hour: 2, combine:"", reading: "",},
            {subject: "专题六：文言文巩固2",subjectCombine:"", content: "《木兰诗》重点实词虚词解释、课文解析及阅读拓展", hour: 2, combine:"", reading: "",},
            {subject: "专题七：评价人物形象，学习人物精神",subjectCombine:"", content: "《邓稼先》《闻一多先生的说和做》课文主旨、人物分析", hour: 2, combine:"", reading: "",},
            {subject: "专题八： 期中复习",subjectCombine:"", content: " 课内重点课文、字音字形、古诗文", hour: 2, combine:"", reading: "",},
            {subject: "专题九： 小说阅读",subjectCombine:"", content: " 《社戏》课文内容理解、小说文体知识及阅读", hour: 2, combine:"", reading: "",},
            {subject: "专题十：文言文巩固3",subjectCombine:"", content: "《口技》重点实词虚词解释、课文解析及文言文阅读拓展", hour: 2, combine:"", reading: "",},
            {subject: "专题十一：写作",subjectCombine:"", content: "写人作文方法指导：写人要抓住特点", hour: 2, combine:"", reading: "",},
            {subject: "专题十二： 理解课文主旨",subjectCombine:"", content: "《伟大的悲剧》《在沙漠中心》课文主旨理解及阅读拓展", hour: 2, combine:"", reading: "",},
            {subject: "专题十三： 文言文巩固4",subjectCombine:"", content: "《狼》重点实词虚词解释、课文解析及文言文阅读拓展", hour: 2, combine:"", reading: "",},
            {subject: "专题十四：现代文阅读理解",subjectCombine:"", content: "标题的含义作用、句子的理解、人物形象的分析", hour: 6, combine:"", reading: "",},
            {subject: "专题十五：写作",subjectCombine:"", content: "描写要生动及习作点评与修改", hour: 2, combine:"", reading: "",},
            {subject: "专题十六：名著导读",subjectCombine:"", content: "《童年》《昆虫记》名著导读", hour: 2, combine:"", reading: "",},
            {subject: "专题十七：期末复习",subjectCombine:"", content: " 课内重点课文、字音字形、古诗文、阅读、写作", hour: 4, combine:"", reading: "",},
        ],
        math: [
            {subject: "专题一：相交线与平行线",subjectCombine:"4", content: " 相交线、垂线、同位角、内错角、同旁内角", hour: 2, combine:"999", reading: "同步提高为主，本阶段课程计划安排40课时，课程内容紧扣初一下册重难点，从教材出发明确单元重点，同时在此基础上进行延伸拓展，侧重知识点及答题方法和技巧的梳理。建议学生在学习过程中如有问题及时提出，具体教学可根据学生掌握情况适当调整。",},
            {subject: "",subjectCombine:"", content: " 平行线及平行线3种判定", hour: 2, combine:"", reading: "",},
            {subject: "",subjectCombine:"", content: " 平行线的性质、命题、定理、证明", hour: 2, combine:"", reading: "",},
            {subject: "",subjectCombine:"", content: " 平行线的构造、平移及其画法", hour: 2, combine:"", reading: "",},
            {subject: "专题二：实数",subjectCombine:"3", content: " 根式的运算", hour: 2, combine:"", reading: "",},
            {subject: "",subjectCombine:"", content: " 非负性应用", hour: 2, combine:"", reading: "",},
            {subject: "",subjectCombine:"", content: " 数轴与应用", hour: 2, combine:"", reading: "",},
            {subject: "期中复习",subjectCombine:"", content: " 根据模考卷情况，进行查漏补缺", hour: 2, combine:"", reading: "",},
            {subject: "专题三：平面直角坐标系",subjectCombine:"3", content: " 有序数对、平面直角坐标系", hour: 2, combine:"", reading: "",},
            {subject: "",subjectCombine:"", content: " 坐标方法的简单应用", hour: 2, combine:"", reading: "",},
            {subject: "",subjectCombine:"", content: " 特殊点的坐标特征、平面直角坐标系中面积求法", hour: 2, combine:"", reading: "",},
            {subject: "专题四：二元一次方程组",subjectCombine:"4", content: " 二元一次方程组解法（代入消元、加减消元）", hour: 2, combine:"", reading: "",},
            {subject: "",subjectCombine:"", content: " 含参二元一次方程组", hour: 2, combine:"", reading: "",},
            {subject: "",subjectCombine:"", content: " 实际问题与二元一次方程组", hour: 2, combine:"", reading: "",},
            {subject: "",subjectCombine:"", content: " 三元一次方程组的解法", hour: 2, combine:"", reading: "",},
            {subject: "专题五：不等式与不等式组",subjectCombine:"3", content: " 不等式及其解集、不等式的性质", hour: 2, combine:"", reading: "",},
            {subject: "",subjectCombine:"", content: " 解一元一次不等式（组）", hour: 2, combine:"", reading: "",},
            {subject: "",subjectCombine:"", content: " 一元一次不等式的应用", hour: 2, combine:"", reading: "",},
            {subject: "专题六：数据的收集",subjectCombine:"", content: " 统计调查、直方图", hour: 2, combine:"", reading: "",},
            {subject: "期末复习",subjectCombine:"", content: " 根据模考卷情况，进行查漏补缺", hour: 2, combine:"", reading: "",},
        ],
        English: [
            {subject: "专题一：情态动词",subjectCombine:"", content: " 重点讲解情态动词can、have to、must的用法", hour: 4, combine:"", reading: "清楚各情态动词的基本含义和用法，并结合相应的练习精准掌握",},
            {subject: "专题二：频度副词",subjectCombine:"", content: " 重点讲解频度副词never、usually的用法", hour: 2, combine:"", reading: "结合生活中的例子，学习如何用never、usually等词汇表达日常生活中做事情的次数",},
            {subject: "专题三：how引导的特殊疑问句 ",subjectCombine:"", content: " 讲解how引导的特殊疑问句", hour: 2, combine:"", reading: "特殊疑问词how表示方式方法，并学会提问",},
            {subject: "专题四：why引导的特殊疑问句",subjectCombine:"", content: " 讲解why引导的特殊疑问句", hour: 2, combine:"", reading: "特殊疑问词why表示原因，原由，并学会用why进行提问",},
            {subject: "专题五：第三人称的用法 ",subjectCombine:"", content: " 第三人称的表达", hour: 2, combine:"", reading: "当主语为第三人称时，其谓语动词的变化是本学期学习重点",},
            {subject: "专题六：名词的数 ",subjectCombine:"", content: " 可数名词与不可数名词的辨别和可数名词的单数变复数", hour: 4, combine:"", reading: "名词单复数的辨析以及使用及常考题练习",},
            {subject: "专题七：现在进行时态",subjectCombine:"", content: " 现在进行时的理解、判别、运用", hour: 2, combine:"", reading: "对现在进行时态的概念用法及考点有系统的认识，运用现在进行时进行写作",},
            {subject: "专题八：where引导的特殊疑问句 ",subjectCombine:"", content: " 讲解where引导的特殊疑问句", hour: 2, combine:"", reading: "特殊疑问词where用来提问地点，学会对不同地点进行提问",},
            {subject: "专题九：there be 句型",subjectCombine:"", content: " 讲解there be句型", hour: 4, combine:"", reading: "There be句型的基本结构，主谓一致，反义疑问句以及其与have的替换",},
            {subject: "专题十： 一般过去时态",subjectCombine:"", content: " 讲解一般过去时态", hour: 4, combine:"", reading: "Be动词的一般过去时态的词形变化是本节课重点",},
            {subject: "专题十一： 阅读专项讲解",subjectCombine:"", content: " 阅读", hour: 6, combine:"", reading: "讲解阅读题解题技巧以及练习题讲解",},
            {subject: "专题十二： 写作专项讲解",subjectCombine:"", content: " 写作", hour: 6, combine:"", reading: "讲解写作技巧以及练笔讲解",},
        ]
    },
    middle_t: {
        Chinese: [
            {subject: "专题一：现代文阅读",subjectCombine:"", content: " 《藤野先生》课文内容理解、理解词语的含义、理解重点句子的含义", hour: 4, combine:"999", reading: "本阶段课程计划安排40课时，课程内容紧扣初二下册重难点，从教材出发明确单元重点，同时在此基础上进行延伸拓展，侧重知识点及答题方法和技巧的梳理。建议学生在学习过程中如有问题及时提出，具体教学可根据学生掌握情况适当调整。",},
            {subject: "专题二：阅读理解作用类题型",subjectCombine:"", content: " 人物描写、环境描写、关键句子和段落的作用", hour: 4, combine:"", reading: "",},
            {subject: "专题三：散文阅读",subjectCombine:"", content: " 《雪》课文内容理解、联想与想象、直接抒情与间接抒情", hour: 4, combine:"", reading: "",},
            {subject: "专题四：说明文阅读",subjectCombine:"", content: " 说明对象及其特点概括、说明方法及作用、说明顺序、说明文语言特点", hour: 4, combine:"", reading: "",},
            {subject: "专题五：写作",subjectCombine:"", content: " 命题作文与半命题作文写作方法指导", hour: 2, combine:"", reading: "",},
            {subject: "专题六：期中复习",subjectCombine:"", content: " 课内重点课文、字音字形、古诗文", hour: 2, combine:"", reading: "",},
            {subject: "专题七：短语结构类型和句子成分",subjectCombine:"", content: " 辨析短语类型、划分单句句子成分", hour: 2, combine:"", reading: "",},
            {subject: "专题八：标点符号的用法",subjectCombine:"", content: " 正确运用标点符号、了解常见标点符号的作用", hour: 2, combine:"", reading: "",},
            {subject: "专题九：现代文阅读理解",subjectCombine:"", content: " 阅读常见题型、答题方法和技巧", hour: 2, combine:"", reading: "",},
            {subject: "专题十： 课内古诗文巩固1",subjectCombine:"", content: " 《与朱元思书》《送东阳马生序》《诗词曲五首》", hour: 2, combine:"", reading: "",},
            {subject: "专题十一： 课内古诗文巩固2",subjectCombine:"", content: " 《小石潭记》《岳阳楼记》《醉翁亭记》《诗五首》", hour: 4, combine:"", reading: "",},
            {subject: "专题十人：写作",subjectCombine:"", content: " 把内容写具体、学会描写与抒情", hour: 2, combine:"", reading: "",},
            {subject: "专题三：名著导读",subjectCombine:"", content: " 《海底两万里》《名人传》名著导读", hour: 2, combine:"", reading: "",},
            {subject: "专题十四： 期末复习",subjectCombine:"", content: " 课内重点课文、字音字形、古诗文、阅读、写作", hour: 4, combine:"", reading: "",},
        ],
        math: [
            {subject: "专题一：二次根式",subjectCombine:"3", content: " 二次根式、有意义的条件", hour: 2, combine:"999", reading: "同步提高为主，本阶段课程计划安排40课时，课程内容紧扣初二下册重难点，从教材出发明确单元重点，同时在此基础上进行延伸拓展，侧重知识点及答题方法和技巧的梳理。建议学生在学习过程中如有问题及时提出，具体教学可根据学生掌握情况适当调整",},
            {subject: "",subjectCombine:"", content: " 化简、最简二次根式", hour: 2, combine:"", reading: "",},
            {subject: "",subjectCombine:"", content: " 二次根式的四则运算", hour: 2, combine:"", reading: "",},
            {subject: "专题二：勾股定理",subjectCombine:"3", content: " 勾股定理、直角三角形边长的数量关系", hour: 2, combine:"", reading: "",},
            {subject: "",subjectCombine:"", content: " 勾股定理的逆定理、方程思想", hour: 2, combine:"", reading: "",},
            {subject: "",subjectCombine:"", content: " 直角三角形的判定", hour: 2, combine:"", reading: "",},
            {subject: "期中复习",subjectCombine:"", content: " 根据模考卷情况，进行查漏补缺", hour: 2, combine:"", reading: "",},
            {subject: "专题三：平行四边形",subjectCombine:"5", content: " 平行四边形的性质、平行四边形的判定、应用", hour: 4, combine:"", reading: "",},
            {subject: "",subjectCombine:"", content: " 三角形中位线、直角三角形斜边中线", hour: 2, combine:"", reading: "",},
            {subject: "",subjectCombine:"", content: " 矩形的性质、矩形的判定、应用", hour: 2, combine:"", reading: "",},
            {subject: "",subjectCombine:"", content: " 菱形的性质、菱形的判定、应用", hour: 2, combine:"", reading: "",},
            {subject: "",subjectCombine:"", content: " 正方形的性质、正方形的判定、常见模型", hour: 2, combine:"", reading: "",},
            {subject: "专题四：一次函数",subjectCombine:"3", content: " 变量与函数、函数的图像、正比例函数解析式及其图像性质", hour: 2, combine:"", reading: "",},
            {subject: "",subjectCombine:"", content: " 一次函数解析式、一次函数图像及其性质", hour: 2, combine:"", reading: "",},
            {subject: "",subjectCombine:"", content: " 一次函数的应用、一次函数与方程/不等式", hour: 4, combine:"", reading: "",},
            {subject: "专题五：数据的分析",subjectCombine:"2", content: " 平均数、加权平均数、中位数、众数", hour: 2, combine:"", reading: "",},
            {subject: "",subjectCombine:"", content: " 方差、标准差", hour: 2, combine:"", reading: "",},
            {subject: "期末复习",subjectCombine:"", content: " 根据模考卷情况，进行查漏补缺", hour: 2, combine:"", reading: "",},
        ],
        English: [
            {subject: "专题一：过去进行时态",subjectCombine:"", content: " 讲解过去进行时态", hour: 4, combine:"", reading: "清楚掌握过去进行时态的构成和用法，并结合相应的练习精准掌握",},
            {subject: "专题二：when/while ",subjectCombine:"", content: " When/while引导的时间状语从句", hour: 2, combine:"", reading: "When/while引导的时间状语从句的区别",},
            {subject: "专题三：should/could ",subjectCombine:"", content: " should/could表示建议的用法", hour: 2, combine:"", reading: "利用情态动词表示委婉的建议",},
            {subject: "专题四：一般将来时态",subjectCombine:"", content: " be going to/will构成的一般将来时态", hour: 4, combine:"", reading: "讲解一般将来时态的构成与用法，辨析be going to 和will表示一般将来时态的区别",},
            {subject: "专题五：现在完成进行时",subjectCombine:"", content: " 现在完成时态的讲解", hour: 2, combine:"", reading: "现在完成进行时have been doing与一般过去时态的区别",},
            {subject: "专题六：现在完成时态",subjectCombine:"", content: " 现在完成时态的讲解", hour: 4, combine:"", reading: "现在完成时态的构成及用法",},
            {subject: "专题七：词组辨析",subjectCombine:"", content: " 义近词辨析", hour: 2, combine:"", reading: "So/neither的区别，have been to/have gone to的区别",},
            {subject: "专题八：反义疑问句 ",subjectCombine:"", content: " 反义疑问句", hour: 2, combine:"", reading: "反义疑问句的时态与人称的一致，含有否定意义的词汇集锦",},
            {subject: "专题九：完形填空专项讲解",subjectCombine:"", content: " 完形填空", hour: 6, combine:"", reading: "讲解完形填空题解题技巧以及练习题讲解",},
            {subject: "专题十： 阅读专项讲解",subjectCombine:"", content: " 阅读", hour: 6, combine:"", reading: "讲解阅读题解题技巧以及练习题讲解",},
            {subject: "专题十一： 写作专项讲解",subjectCombine:"", content: " 写作", hour: 6, combine:"", reading: "讲解写作技巧以及练笔讲解",},
        ],
        Physics:[
            {subject: "专题一：力",subjectCombine:"", content: " 力的作用效果，表示方法，弹簧测力计的使用，弹力，重力的大小和方向，重心 ", hour: 4, combine:"", reading: "力是学习后续课程的基础，一定要熟练掌握",},
            {subject: "专题二：牛顿第一定律",subjectCombine:"", content: " 运动和力的关系，牛顿第一定律，惯性及惯性现象", hour: 2, combine:"3", reading: "运动和力的关系是力学所要解决的中心课题，也是物理学的基础，通过学习培养学生对事物的认知能力，并进一步体验物理学的研究方法",},
            {subject: "专题三：二力平衡",subjectCombine:"", content: " 二力平衡的条件及应用，二力平衡和相互作用的区别", hour: 2, combine:"", reading: "",},
            {subject: "专题四：摩擦力",subjectCombine:"", content: " 摩擦力产生的条件，滑动摩擦力大小的影响因素，根据运动状态判断摩擦力的大小，摩擦的利用与防止", hour: 2, combine:"", reading: "",},
            {subject: "专题五：压强",subjectCombine:"", content: " 影响压力作用效果的因素，怎样减小或增大压强", hour: 2, combine:"4", reading: "压强是初中物理中有关力学知识的一次较大的综合，压力、压强与人们的日常生活、生产技术有着密切的联系，在压强概念的学习中，学习运用比值定义法和类比法等科学方法，重点是压强大小决定因素及其概念的理解",},
            {subject: "专题六：液体的压强",subjectCombine:"", content: " 液体压强的特点，公式，连通器", hour: 2, combine:"", reading: "",},
            {subject: "专题七：流体压强",subjectCombine:"", content: " 大气压强的大小和测量，流体压强与流速的关系", hour: 2, combine:"", reading: "",},
            {subject: "专题八：压强章节复习",subjectCombine:"", content: " 压强章节的知识梳理和重难点分析", hour: 2, combine:"", reading: "",},
            {subject: "专题九：浮力",subjectCombine:"", content: " 浮力的定义，决定浮力大小的因素", hour: 2, combine:"4", reading: "浮力综合应用了液体压强、压力、二力平衡等知识，本章重点和关键是浮力的利用，浮力知识对人们的日常生活、生产技术和科学研究有着广泛的现实意义。",},
            {subject: "专题十：阿基米德原理",subjectCombine:"", content: " 阿基米德原理的内容，浮力大小的计算公式", hour: 2, combine:"", reading: "",},
            {subject: "专题十一：物体的浮沉条件及应用",subjectCombine:"", content: " 物体的浮沉条件，浮力的应用，浮力问题的综合运算", hour: 2, combine:"", reading: "",},
            {subject: "专题十二：浮力章节复习",subjectCombine:"", content: " 浮力章节的知识梳理和重难点分析", hour: 2, combine:"", reading: "",},
            {subject: "专题十三：功和功率",subjectCombine:"", content: " 功的定义和计算，力不做功的实例，功率的计算", hour: 2, combine:"3", reading: "功和机械能具有很强的综合性，是对力学知识进行总结和升华的重要章节，通过动能和势能以及机械能及其转化的内容的学习，使学生认识力学中的功和能的关系，为后续学习内能以及能量转化和守恒定律打下基础",},
            {subject: "专题十四：机械能及其转化",subjectCombine:"", content: " 动能和势能大小的影响因素，机械能及其转化", hour: 2, combine:"", reading: "",},
            {subject: "专题十五：功和机械能复习",subjectCombine:"", content: " 功和机械能章节的知识梳理和重难点分析", hour: 2, combine:"", reading: "",},
            {subject: "专题十六：杠杆",subjectCombine:"", content: " 杠杆的五要素，杠杆的平衡条件，生活中的杠杆", hour: 2, combine:"3", reading: "简单机械注重从与日常生活关系最密切的实例入手，学生既能学到物理知识，也能够经历科学研究的分析过程，认识到在不同的现象中会蕴含着相同的物理规律的认识体验。",},
            {subject: "专题十七：滑轮、机械效率",subjectCombine:"", content: " 定滑轮和动滑轮的特点，滑轮组，有用功和无用功，机械效率", hour: 2, combine:"", reading: "",},
            {subject: "专题十八：简单机械复习",subjectCombine:"", content: " 简单机械章节的知识梳理和重难点分析", hour: 2, combine:"", reading: "",},
            {subject: "专题十九：期末复习",subjectCombine:"", content: " 本学期重要知识点梳理和重难点分析", hour: 2, combine:"", reading: "--",},
        ]
    },
    middle_th: {
        Chinese: [
            {subject: "语言文字运用",subjectCombine:"6", content: " 专题汇编：字音和字形", hour: 2, combine:"999", reading: "本阶段课程计划安排40课时，课程内容主要是根据考纲要求，进行各模块知识点的系统复习。同时，侧重答题方法和技巧的梳理，通过真题模拟练习加深学生对知识的理解。建议学生在学习过程中如有问题及时提出，具体教学可根据学生掌握情况适当调整。",},
            {subject: "",subjectCombine:"", content: " 专题汇编：词语和成语", hour: 2, combine:"", reading: "",},
            {subject: "",subjectCombine:"", content: " 专题汇编：病句辨析与修改", hour: 2, combine:"", reading: "",},
            {subject: "",subjectCombine:"", content: " 专题汇编：标点符号", hour: 2, combine:"", reading: "",},
            {subject: "",subjectCombine:"", content: " 专题汇编：句子衔接、排序、仿写与对联(含修辞)", hour: 2, combine:"", reading: "",},
            {subject: "",subjectCombine:"", content: " 专题汇编：语言运用与综合性学习(含传统文化)", hour: 2, combine:"", reading: "",},
            {subject: "古诗文",subjectCombine:"4", content: " 专题汇编：文学常识与名著阅读", hour: 2, combine:"", reading: "",},
            {subject: "",subjectCombine:"", content: " 专题汇编：名句名篇默写", hour: 2, combine:"", reading: "",},
            {subject: "",subjectCombine:"", content: " 专题汇编：古诗词鉴赏", hour: 2, combine:"", reading: "",},
            {subject: "",subjectCombine:"", content: " 专题汇编：文言文阅读", hour: 2, combine:"", reading: "",},
            {subject: "现代文阅读",subjectCombine:"3", content: " 专题汇编：记叙文阅读", hour: 4, combine:"", reading: "",},
            {subject: "",subjectCombine:"", content: " 专题汇编：说明文阅读", hour: 4, combine:"", reading: "",},
            {subject: "",subjectCombine:"", content: " 专题汇编：议论文阅读", hour: 4, combine:"", reading: "",},
            {subject: "写作",subjectCombine:"", content: " 专题汇编：写作", hour: 2, combine:"", reading: "",},
            {subject: "考前冲刺",subjectCombine:"3", content: " 中考考前冲刺1", hour: 2, combine:"", reading: "",},
            {subject: "",subjectCombine:"", content: " 中考考前冲刺2", hour: 2, combine:"", reading: "",},
            {subject: "",subjectCombine:"", content: " 中考考前冲刺3", hour: 2, combine:"", reading: "",},
        ],
        math: [
            {subject: "专题一：数学思想方法",subjectCombine:"", content: " 分类讨论思想、数形结合思想、化归转化思想、数学建模思想", hour: 2, combine:"7", reading: "数学思想、阅读理解、方案设计和问题探索是中考解题中重要的思维能力，也是中考数学重要内容。只有掌握正确的方法，才能真正做好题。在给学生具体梳理完中考知识点之后，给学生具体划分模块，理顺解题思路，便于后续真题练习。",},
            {subject: "专题二：阅读理解问题",subjectCombine:"", content: " 新定义学习型、新公式应用型、新解题方法型、归纳概括型", hour: 2, combine:"", reading: "",},
            {subject: "专题三：方案设计问题",subjectCombine:"", content: " 方程不等式型、函数型、几何图形型、测量方案型", hour: 2, combine:"", reading: "",},
            {subject: "专题四：开放探索问题",subjectCombine:"", content: " 条件开放探索、结论开放探索、规律开放探索、存在性开放探索", hour: 2, combine:"", reading: "",},
            {subject: "专题五：动态探索问题",subjectCombine:"2", content: " 动点与函数图像问题、动点问题探索", hour: 2, combine:"", reading: "",},
            {subject: "",subjectCombine:"", content: " 图形运动与函数图像问题、图形运动问题探索", hour: 2, combine:"", reading: "",},
            {subject: "专题六：选择题的解法",subjectCombine:"", content: " 直接法求解、验证法求解、排除法求解、特殊值或特殊位置求解、分析法或简单推理求解、动手操作法求解、综合法", hour: 2, combine:"", reading: "",},
            {subject: "专题七：基础题训练一",subjectCombine:"", content: " 精选真题（去掉填空最后一题和解答最后2题），定时限时训练", hour: 2, combine:"2", reading: "精选中考真题，让学生定时按中考要求做限时训练，保证正确率和速度。程度稍差学生重点是这一部分，多做练习，保证基础题会做能做对。",},
            {subject: "专题八：基础题训练二",subjectCombine:"", content: " 精选真题（去掉填空最后一题和解答最后2题），定时限时训练", hour: 2, combine:"", reading: "",},
            {subject: "专题九：填空压轴题一",subjectCombine:"", content: " 精选真题，翻折和旋转", hour: 2, combine:"5", reading: "精选中考真题，探索中考出题模式，按具体题目分析解题思路",},
            {subject: "专题十：填空压轴题二",subjectCombine:"", content: " 精选真题，平移、新定义", hour: 2, combine:"", reading: "",},
            {subject: "专题十一：几何证明与计算",subjectCombine:"", content: " 精选真题中档题和压轴题", hour: 4, combine:"", reading: "",},
            {subject: "专题十二：几何图形中的函数问题",subjectCombine:"", content: " 精选真题压轴题", hour: 4, combine:"", reading: "",},
            {subject: "专题十三：函数图像中的几何问题",subjectCombine:"", content: " 精选真题压轴题", hour: 4, combine:"", reading: "",},
            {subject: "专题十四：知识点查漏补缺",subjectCombine:"", content: " 根据模考卷情况，进行查漏补缺", hour: 2, combine:"3", reading: "冲刺和押题卷不会太难，为学生考前练手准备，最后冲刺的几周调整心态比学习较难的知识更重要。",},
            {subject: "专题十五：中考押题卷一",subjectCombine:"", content: " 教研根据高考考纲和历年出题规律，提炼高考押题卷", hour: 2, combine:"", reading: "",},
            {subject: "专题十六：中考押题卷二",subjectCombine:"", content: " 教研根据高考考纲和历年出题规律，提炼高考押题卷", hour: 2, combine:"", reading: "",},
        ],
        English: [
            {subject: "专题一：units1~5",subjectCombine:"", content: " 七年级上册units1~5词汇、重点语法、阅读", hour:2, combine:"", reading: "指示代词：this，these，that，those<br>物主代词mine，yours, his, hers<br>方位介词on, in ,under"},
            {subject: "专题二：units6~10",subjectCombine:"", content: " 七年级上册units6~10词汇、重点语法、阅读", hour:2, combine:"", reading: "基数词与序数词<br>名词的数（可数名词与不可数名词）<br>谈论日期的表达<br>谈论喜好并说明理由"},
            {subject: "专题三：units1~4",subjectCombine:"", content: " 七年级下册units1~4词汇、重点语法、阅读", hour:2, combine:"", reading: "情态动词can表示能力<br>情态动词can表示允许<br>频度副词<br>Take, spend, pay表示花费的区别<br>How questions"},
            {subject: "专题四：units5~8",subjectCombine:"", content: " 七年级下册units5~8词汇、重点语法、阅读", hour:2, combine:"", reading: "现在进行时态<br>There be 句型"},
            {subject: "专题五：units9~12",subjectCombine:"", content: " 七年级下册units9~12词汇、重点语法、阅读", hour:2, combine:"", reading: "选择疑问句<br>一般过去时态<br>some/any"},
            {subject: "专题六：units1~2",subjectCombine:"", content: " 八年级上册units1~2词汇、重点语法、阅读", hour:2, combine:"", reading: "不定代词动词<br>过去式（规则变化及不规则变化）<br>频度副词"},
            {subject: "专题七：units3~4",subjectCombine:"", content: " 八年级上册units3~4词汇、重点语法、阅读", hour:2, combine:"", reading: "形容词、副词的比较级与最高级"},
            {subject: "专题八：units5~6",subjectCombine:"", content: " 八年级上册units5~6词汇、重点语法、阅读", hour:2, combine:"", reading: "不定式<br>一般将来时态"},
            {subject: "专题九：units7~8",subjectCombine:"", content: " 八年级上册units7~8词汇、重点语法、阅读", hour:2, combine:"", reading: "Will表示将来 <br>More， less， fewer表示数量"},
            {subject: "专题十：units7~8",subjectCombine:"", content: " 八年级上册units9~10词汇、重点语法、阅读", hour:2, combine:"", reading: "Can表示邀请及情态动词might的用法 <br>If引导的条件状语从句"},
            {subject: "专题十一：units1~2",subjectCombine:"", content: " 八年级下册units1~2词汇、重点语法、阅读", hour:2, combine:"", reading: "情态动词should/shouldn't表建议 <br> 反身代词 <br>不定代词作宾语，状语和宾语补足语"},
            {subject: "专题十二：Units3~4",subjectCombine:"", content: " 八年级下册Units3~4词汇、重点语法、阅读", hour:2, combine:"", reading: "情态动词could的用法 <br>谈论问题，给出建议"},
            {subject: "专题十三：units5~6",subjectCombine:"", content: " 八年级下册units5~6词汇、重点语法、阅读", hour:2, combine:"", reading: "when/while 的区别 <br>过去进行时态 <br>Unless/ as soon as/ so… that"},
            {subject: "专题十四：units7~8",subjectCombine:"", content: " 八年级下册units7~8词汇、重点语法、阅读", hour:2, combine:"", reading: "用形容词、副词的比较级和最高级谈论自然景观 <br>现在完成时态"},
            {subject: "专题十五：units9~10",subjectCombine:"", content: " 九年级units9~10词汇、重点语法、阅读", hour:2, combine:"", reading: "现在完成时态 <br>Already/ yet <br>Ever/ never <br>Since/ for"},
            {subject: "专题十六：units1~3",subjectCombine:"", content: " 九年级units1~3词汇、重点语法、阅读", hour:2, combine:"", reading: "By with gerund表示方式方法 <br>宾语从句"},
            {subject: "专题十七：units4~6",subjectCombine:"", content: " 九年级units4~6词汇、重点语法、阅读", hour:2, combine:"", reading: "被动语态"},
            {subject: "专题十八：units7~8",subjectCombine:"", content: " 九年级units7~8词汇、重点语法、阅读", hour:2, combine:"", reading: "Must/might/could/can’t"},
            {subject: "专题十九：units9~10",subjectCombine:"", content: " 九年级units9~10词汇、重点语法、阅读", hour:2, combine:"", reading: "定语从句"},
            {subject: "专题二十：unit11~12",subjectCombine:"", content: " 九年级unit11~12词汇、重点语法、阅读", hour:2, combine:"", reading: "过去完成时态"},
            {subject: "专题二十一：unit13~14",subjectCombine:"", content: " 九年级unit13~14", hour:2, combine:"", reading: "复习本册主要内容"},
        ],
        Physics:[
            {subject: "专题一：电与磁",subjectCombine:"", content: " 磁现象、磁场，电生磁，电磁铁、电磁继电器，电动机，磁生电", hour: 2, combine:"", reading: "电与磁要求学生会运用磁极及其相互作用规律解释简单的磁现象，探究导体在磁场中运动时产生感应电流的条件",},
            {subject: "专题二：信息的传递能源和可持续性发展",subjectCombine:"", content: " 电话，电磁波的产生和传播，广播、电视和移动通信，能源，核能，太阳能，能源与可持续性发展", hour: 1, combine:"", reading: "这部分内容体现了教材内容的时代性，课程标准对其要求不高，主要是了解。",},
            {subject: "专题四：机械运动复习",subjectCombine:"", content: " 估测时间和长度，托盘天平的使用和注意事项，误差和错误，参照物，运动和静止的相对性，能用速度描述物体的运动，通过实验测定物体的运动速度，S-t图像，用速度公式进行简单计算", hour: 2, combine:"", reading: "知道参照物的概念 ，知道物体的运动和静止是相对的，能用速度描述物体的运动，能用速度公式进行简单的计算，知道匀速直线运动的概念 ，会使用适当的工具测量时间和长度，知道测量有误差，误差和错误有区别",},
            {subject: "专题五：声现象复习",subjectCombine:"", content: " 声的产生和传播条件，乐音的特性，噪声的危害和控制的方法", hour: 1, combine:"", reading: "声音的产生和传播的条件，乐音的特征，防控噪声的途径是重点， 难点是音调、响度和音色的区分，超声波特点利用、次声波的危害及在生活中的应用。",},
            {subject: "专题六：物态变化复习",subjectCombine:"", content: " 液体温度计的工作原理，用常见温度计测量温度，物质的熔点、凝固点和沸点，物态变化过程中的吸热和放热现象，水的三态变化", hour: 1, combine:"", reading: "学会正确使用液体温度计，认识熔化、凝固、蒸发、沸腾、液化、升华、凝华现象及其吸、放热情况，能用熔点解释简单的现象，知道沸点与压强的关系，能用来解释简单的现象，认识蒸发快慢的影响因素，并能用来解释简单的现象",},
            {subject: "专题七：光现象复习",subjectCombine:"", content: " 光的传播，反射，平面镜成像，折射，凸透镜成像的规律", hour: 2, combine:"", reading: "学习探究光在同种均匀介质中传播的特点并了解光的反射和折射的规律，通过实验探究平面镜成像时像与物的关系，认识凸透镜的会聚作用和凹透镜的发散作用，知道白光是色光组成的，比较色光混合与颜料混合的不同现象",},
            {subject: "专题八：质量与密度复习",subjectCombine:"", content: " 质量，质量的测量，密度，测量物质的密度，密度与社会生活", hour: 1, combine:"", reading: "初步认识质量的概念，会测量固体和液体的质量，理解密度的概念，尝试用密度知识解决简单的问题，能解释生活中一些与密度有关的物理现象，了解物质的属性对科技进步的影响",},
            {subject: "专题九：运动和力复习",subjectCombine:"", content: " 重力、弹力和摩擦力，力的作用效果，用示意图描述力，弹簧测力计，二力平衡条件，牛顿第一定律，惯性", hour: 2, combine:"", reading: "知道牛顿第一定律，理解惯性的概念，能用惯性解释生活中产生有关现象，知道二力平衡的概念及二力平衡的条件，知道摩擦力的概念、摩擦力大小与什么因素有关及增大和减小摩擦力的方法",},
            {subject: "专题十：压强和浮力复习",subjectCombine:"", content: " 影响压力作用效果的因素，怎样减小或增大压强，液体压强的特点，公式，连通器，大气压强的大小和测量，流体压强与流速的关系", hour: 2, combine:"", reading: "理解压强，探究并了解液体压强与哪些因素有关，知道大气压强与人类生活的关系，了解流体的压强与流速的关系及其在生活中的应用，认识浮力，理解阿基米德原理",},
            {subject: "专题十一：功和机械能复习",subjectCombine:"", content: " 动能和势能的相互转化，机械功和功率，做功的两个必要因素，机械效率，提高机械效率的途径和意义", hour: 1, combine:"", reading: "知道机械功和功率，知道动能、势能和机械能，可以说明机械能和其他形式能量的相互转化，中考常考判断物体是否做功",},
            {subject: "专题十二：简单机械复习",subjectCombine:"", content: " 杠杆的五要素，杠杆的平衡条件，生活中的杠杆，定滑轮和动滑轮的特点，滑轮组，有用功和无用功，机械效率", hour: 1, combine:"", reading: "知道简单机械，通过实验，探究并了解杠杆的平衡条件，知道机械效率，了解提高机械效率的途径和意义，了解机械的使用对社会发展的作用",},
            {subject: "专题十三：内能和热机复习",subjectCombine:"", content: " 内能和热量，比热容，热机的工作原理，内能的利用在人类社会发展史上的重要意义，热机的效率，能量的转化和守恒", hour: 2, combine:"", reading: "中考考查重点是分子动理论，内能和改变内能的两种方式，比热容，热量及其计算，掌握热机的工作原理，会计算热机的效率，理解能量守恒定律，以填空题、选择题、计算题、综合能力题为主",},
            {subject: "专题十四：电流和电路 电压 电阻复习",subjectCombine:"", content: " 两种电荷，电流和电路，串联和并联，电流的测量，电压，电阻，串并联电路中电流、电压、电阻的规律，变阻器，电压表滑动变阻器的使用和对电阻的理解（重点）", hour: 2, combine:"", reading: "摩擦起电，认识电源和用电器的作用，会看、会画、会连接简单的串联电路和并联电路，知道电流、电压和电阻，了解串并联电路中的电流电压和电阻特点，能灵活运用电压电阻解决电路中的相关问题。",},
            {subject: "专题十五：欧姆定律复习",subjectCombine:"", content: " 电流与电压和电阻的关系，欧姆定律及其应用，电阻的测量， ", hour: 2, combine:"", reading: "欧姆定律的理解和应用，动态电路的分析，串并联电路中电压、电流和电阻的关系，伏安法测电阻是高频考点",},
            {subject: "专题十六：电功率复习",subjectCombine:"", content: " 电能，电功，电功率，测量小灯泡的电功率，焦耳定律，电路故障分析", hour: 2, combine:"", reading: "结合实例理解电功、电功率，知道用电器的额定功率和实际功率，用焦耳定律说明生产、生活中的一些现象，电热的计算，测量小灯泡的电功率，电路故障的分析与判断",},
            {subject: "专题十七：生活用电 电与磁复习",subjectCombine:"", content: " 家庭电路，安全用电，磁场，电流的磁效应，电磁铁，电磁继电器，电动机，电磁感应", hour: 2, combine:"", reading: "知道家庭电路组成部分及作用，会用电能表，会连简单家庭电路，知道保险丝作用， 知道家庭电路电流过大的原因，知道触电方式，会触电急救，会运用磁极及其相互作用规律解释简单的磁现象，探究导体在磁场中运动时产生感应电流的条件",},
            {subject: "专题十八：填空、选择、作图题突破及限时训练",subjectCombine:"", content: " 以历年典型模题和真题为基础，进行限时训练，找出错误原因及查漏补缺", hour: 2, combine:"4", reading: "精选中考真题，让学生定时按中考要求做限时训练，保证正确率和速度。程度稍差学生重点是这一部分，多做练习，保证基础题会做能做对，最后主要是根据学生的具体情况有针对性的为学生提供个性化的方案，为中考做好准备！",},
            {subject: "专题十九：计算和实验题突破及限时训练",subjectCombine:"", content: " 以历年典型模题和真题为基础，进行限时训练，找出错误原因及查漏补缺", hour: 4, combine:"", reading: "",},
            {subject: "专题二十一：压轴题分析",subjectCombine:"", content: " 压轴难题的分析和解答方法", hour: 4, combine:"", reading: "",},
            {subject: "专题二十：易错题巩固",subjectCombine:"", content: " 易混淆的知识点、易错题梳理", hour: 4, combine:"", reading: "",},
        ],
        Chemistry:[
            {subject: "金属材料",subjectCombine:"", content: " 金属的物理性质、金属之最、金属的分类和运用、常见的合金", hour: 2, combine:"999", reading: "本部分的的计划课时是40小时，主要在于新课的学习和专题内容的复习，新课内容主要在于知识点的，专题的内容主要根据中考考纲要求做专题的拔高和提升，主要在于重难点的梳理和题型的分析解答，具体操作需要根据学生具体情况作具体分析。",},
            {subject: "金属的化学性质",subjectCombine:"", content: " 金属与氧气反应、金属活泼性、简单的金属冶炼", hour: 2, combine:"", reading: "",},
            {subject: "金属资源的保护和利用",subjectCombine:"", content: " 铁的冶炼、高炉炼铁、金属资源的保护措施", hour: 2, combine:"", reading: "",},
            {subject: "溶液的形成",subjectCombine:"", content: " 溶液的概念和构成、溶解时的吸热或放热现象", hour: 2, combine:"", reading: "",},
            {subject: "溶解度、溶液浓度",subjectCombine:"", content: " 溶解度的概念和注意事项、溶解度的计算、饱和溶液等相关概念的理解与运用、溶质质量分数的计算", hour: 2, combine:"", reading: "",},
            {subject: "一定溶质质量分数溶液的配制",subjectCombine:"", content: " 实验步骤、实验注意事项", hour: 2, combine:"", reading: "",},
            {subject: "常见的酸和碱",subjectCombine:"", content: " 酸碱指示剂、常见的酸和碱、酸碱的化学性质", hour: 2, combine:"", reading: "",},
            {subject: "酸碱中和反应",subjectCombine:"", content: " 中和反应、酸碱PH、酸碱的化学性质和酸碱性检验", hour: 2, combine:"", reading: "",},
            {subject: "生活中的盐、化学肥料、过滤",subjectCombine:"", content: " 常见的盐、复分解反应、化学肥料、过滤实验及步骤", hour: 2, combine:"", reading: "",},
            {subject: "人类重要的营养物质、化学元素和人体健康",subjectCombine:"", content: " 营养物质、化学元素、人体的健康", hour: 2, combine:"", reading: "",},
            {subject: "有机合成材料",subjectCombine:"", content: "  有机物、有机材料", hour: 2, combine:"", reading: "",},
            {subject: "物质的变化和性质",subjectCombine:"", content: " 物理化学性质的区别和联系、物理变化和化学变化的联系和区别", hour: 2, combine:"", reading: "",},
            {subject: "实验室仪器的使用和注意事项",subjectCombine:"", content: " 仪器的名称、实验室仪器的使用、固体和液体液药品的取用、", hour: 2, combine:"", reading: "",},
            {subject: "氧气性质和二氧化碳性质",subjectCombine:"", content: " 氧气与二氧化碳的物理性质和化学性质、氧气与物质反应的现象和实验的注意事项", hour: 2, combine:"", reading: "",},
        ]
    },
    senior_o: {
        Chinese: [
            {subject: "专题一：散文阅读",subjectCombine:"", content: " 《荷塘月色》课文解析、散文文体知识", hour: 2, combine:"999", reading: "本阶段课程计划安排40课时，课程内容紧扣高一下册重难点，从教材出发明确单元重点，同时在此基础上进行延伸拓展，侧重知识点及答题方法和技巧的梳理。建议学生在学习过程中如有问题及时提出，具体教学时可根据学生掌握情况适当调整 。",},
            {subject: "专题二：散文的特点和常见手法",subjectCombine:"", content: " 记叙散文、抒情散文阅读拓展", hour: 4, combine:"", reading: "",},
            {subject: "专题三：小说阅读",subjectCombine:"", content: " 小说文体知识、人物形象、文章内容理解、中心归纳", hour: 4, combine:"", reading: "",},
            {subject: "专题四：诗词鉴赏1",subjectCombine:"", content: " 《诗经》《楚辞》、先秦诗歌发展、诗歌形象、语言鉴赏", hour: 2, combine:"", reading: "",},
            {subject: "专题五：诗词鉴赏2",subjectCombine:"", content: " 山水田园诗、山水田园诗常见意象、山水田园诗常见题型", hour: 4, combine:"", reading: "",},
            {subject: "专题六：写作",subjectCombine:"", content: " 作文的立意及构思指导", hour: 2, combine:"", reading: "",},
            {subject: "专题七：写作",subjectCombine:"", content: " 话题作文写作方法指导", hour: 2, combine:"", reading: "",},
            {subject: "专题八：期中复习",subjectCombine:"", content: " 课内重点课文、字音字形、古诗文", hour: 2, combine:"", reading: "",},
            {subject: "专题九：正确使用词语",subjectCombine:"", content: " 成语：中华文化的微缩景观", hour: 2, combine:"", reading: "",},
            {subject: "专题十：修辞",subjectCombine:"", content: " 语音修辞、词语修辞、语句修辞", hour: 2, combine:"", reading: "",},
            {subject: "专题十一：文言文巩固",subjectCombine:"", content: " 《兰亭集序》《赤壁赋》重点实词虚词、特殊句式", hour: 2, combine:"", reading: "",},
            {subject: "专题十二：文言文阅读",subjectCombine:"", content: " 游记类文言文阅读、作家素材积累、实词虚词积累", hour: 4, combine:"", reading: "",},
            {subject: "专题十三：写作",subjectCombine:"", content: " 学习描写与抒情", hour: 2, combine:"", reading: "",},
            {subject: "专题十四：写作",subjectCombine:"", content: " 材料作文写作方法指导", hour: 2, combine:"", reading: "",},
            {subject: "专题十五：名著导读",subjectCombine:"", content: " 《家》《巴黎圣母院》名著导读", hour: 2, combine:"", reading: "",},
            {subject: "专题十六：期末复习",subjectCombine:"", content: " 课内重点课文、字音字形、古诗文、阅读、写作", hour: 2, combine:"", reading: "",},
        ],
        math: [
            {subject: "专题一：解三角形",subjectCombine:"2", content: " 正弦定理、余弦定理、面积公式", hour: 2, combine:"999", reading: "本阶段课程计划安排40课时，巩固解三角形、数列、不等式、直线方程、圆方程、空间几何体的基本知识，提高常考题型的解题速度与准确率，培养数学思维。建议学生在学习过程中如有问题及时提出，具体教学时可根据学生掌握情况适当调整。",},
            {subject: "",subjectCombine:"", content: " 解三角形题型归纳", hour: 2, combine:"", reading: "",},
            {subject: "专题二：数列",subjectCombine:"5", content: " 等差数列的性质及其判定", hour: 2, combine:"", reading: "",},
            {subject: "",subjectCombine:"", content: " 等差数列的性质及其判定", hour: 2, combine:"", reading: "",},
            {subject: "",subjectCombine:"", content: " 等比数列的性质及其判定", hour: 2, combine:"", reading: "",},
            {subject: "",subjectCombine:"", content: " 数列求和：倒序相加、分组求和、错位相减、裂项相消", hour: 2, combine:"", reading: "",},
            {subject: "",subjectCombine:"", content: " 求数列通项方法汇总", hour: 2, combine:"", reading: "",},
            {subject: "专题三：不等式",subjectCombine:"2", content: " 不等式与常见不等式的解法", hour: 2, combine:"", reading: "",},
            {subject: "",subjectCombine:"", content: " 均值不等式及其应用", hour: 2, combine:"", reading: "",},
            {subject: "期中复习",subjectCombine:"", content: " 根据模考卷情况，进行查漏补缺", hour: 2, combine:"", reading: "",},
            {subject: "专题四：空间几何体",subjectCombine:"4", content: " 三视图和直观图", hour: 2, combine:"", reading: "",},
            {subject: "",subjectCombine:"", content: " 空间几何体的表面积与体积", hour: 2, combine:"", reading: "",},
            {subject: "",subjectCombine:"", content: " 立体几何之平行问题", hour: 2, combine:"", reading: "",},
            {subject: "",subjectCombine:"", content: " 立体几何之垂直问题", hour: 2, combine:"", reading: "",},
            {subject: "专题五：平面解析几何",subjectCombine:"6", content: " 倾斜角与斜率", hour: 2, combine:"", reading: "",},
            {subject: "",subjectCombine:"", content: " 直线方程", hour: 2, combine:"", reading: "",},
            {subject: "",subjectCombine:"", content: " 位置关系与距离公式", hour: 2, combine:"", reading: "",},
            {subject: "",subjectCombine:"", content: " 对称问题与最值问题", hour: 2, combine:"", reading: "",},
            {subject: "",subjectCombine:"", content: " 圆的方程", hour: 2, combine:"", reading: "",},
            {subject: "",subjectCombine:"", content: " 直线（圆）与圆的位置关系", hour: 2, combine:"", reading: "",},
            {subject: "期末复习",subjectCombine:"", content: " 根据模考卷情况，进行查漏补缺", hour: 2, combine:"", reading: "",},
        ],
        English: [
            {subject: "专题一：",subjectCombine:"", content: " Unit 1 Festivals around the world", hour: 2, combine:"", reading: "重点单词、短语、句型、重要语法知识点梳理，课文长难句子分析及相关练习与检测",},
            {subject: "专题二：",subjectCombine:"", content: " Unit2 Healthy eating", hour: 2, combine:"", reading: "重点单词、短语、句型、重要语法知识点梳理，课文长难句子分析及相关练习与检测",},
            {subject: "专题三：",subjectCombine:"", content: " Unit 3 The million pound bank note", hour: 2, combine:"", reading: "重点单词、短语、句型、重要语法知识点梳理，课文长难句子分析及相关练习与检测",},
            {subject: "专题四：",subjectCombine:"", content: " Unit 4Astronomy-science of the stars", hour: 2, combine:"", reading: "重点单词、短语、句型、重要语法知识点梳理，课文长难句子分析及相关练习与检测",},
            {subject: "专题五：",subjectCombine:"", content: " Unit 5Canada-the true north", hour: 2, combine:"", reading: "重点单词、短语、句型、重要语法知识点梳理，课文长难句子分析及相关练习与检测",},
            {subject: "专题六：",subjectCombine:"", content: " Unit 1 Women of achievement", hour: 2, combine:"", reading: "重点单词、短语、句型、重要语法知识点梳理，课文长难句子分析及相关练习与检测",},
            {subject: "专题七：",subjectCombine:"", content: " Unit2 Working the land", hour: 2, combine:"", reading: "重点单词、短语、句型、重要语法知识点梳理，课文长难句子分析及相关练习与检测",},
            {subject: "专题八：",subjectCombine:"", content: " Unit 3 A taste of English humor", hour: 2, combine:"", reading: "重点单词、短语、句型、重要语法知识点梳理，课文长难句子分析及相关练习与检测",},
            {subject: "专题九：",subjectCombine:"", content: " Unit 4 Body language", hour: 2, combine:"", reading: "重点单词、短语、句型、重要语法知识点梳理，课文长难句子分析及相关练习与检测",},
            {subject: "专题十：",subjectCombine:"", content: " Unit 5 Theme parks", hour: 2, combine:"", reading: "重点单词、短语、句型、重要语法知识点梳理，课文长难句子分析及相关练习与检测",},
            {subject: "专题十一：情态动词",subjectCombine:"", content: " 情态动词专项讲解", hour: 2, combine:"", reading: "can, may, must，need, ought to, dare",},
            {subject: "专题十二：主谓一致",subjectCombine:"", content: " 主谓一致", hour: 2, combine:"", reading: "as well as, along with, like, together with, rather than, except, but, 等特殊结构是重点",},
            {subject: "专题十三：名词性从句",subjectCombine:"", content: " 名词性从句", hour: 2, combine:"", reading: "宾语从句和表语从句，主语从句和同位语从句",},
            {subject: "专题十四：虚拟语气",subjectCombine:"", content: " 虚拟语气", hour: 2, combine:"", reading: "这部分是一个难点，可以有针对性的进行强化训练。",},
            {subject: "专题十五：完形填空专项讲解",subjectCombine:"", content: " 完形填空", hour: 3, combine:"", reading: "讲解完形填空题解题技巧以及练习题讲解",},
            {subject: "专题十六： 阅读专项讲解",subjectCombine:"", content: " 阅读", hour: 3, combine:"", reading: "讲解阅读题解题技巧以及练习题讲解",},
            {subject: "专题十七：语法填空",subjectCombine:"", content: " 语法填空", hour: 3, combine:"", reading: "讲解语法填空题解题技巧以及练习题讲解",},
            {subject: "专题十一： 写作专项讲解",subjectCombine:"", content: " 写作", hour: 3, combine:"", reading: "讲解写作技巧以及练笔讲解",},
        ],
        Physics:[
            {subject: "专题一：曲线运动",subjectCombine:"", content: " 曲线运动，关联速度，运动的合成和分解", hour: 2, combine:"5", reading: "会用运动合成与分解的方法分析抛体运动，会描述匀速圆周运动，知道向心加速度，能用牛顿第二定律分析匀速圆周运动的向心力，分析生活和生产中的离心现象，关注抛体运动和圆周运动的规律与日常生活的联系。这部分内容很重要，会用到力的分解和合成，进而求向心力，会结合带电粒子在电场和磁场中的运动来考查。",},
            {subject: "专题二：平抛运动",subjectCombine:"", content: " 平抛运动，研究平抛运动实验", hour: 2, combine:"", reading: "",},
            {subject: "专题三：圆周运动",subjectCombine:"", content: " 圆周运动，向心加速度，向心力", hour: 2, combine:"", reading: "",},
            {subject: "专题四：生活中的圆周运动",subjectCombine:"", content: " 生活中的圆周运动，离心运动", hour: 2, combine:"", reading: "",},
            {subject: "专题五：曲线运动章节复习",subjectCombine:"", content: " 复习归纳本章重要知识", hour: 2, combine:"", reading: "",},
            {subject: "专题六：太阳与行星 ",subjectCombine:"", content: " 行星的运动，太阳与行星间的引力", hour: 2, combine:"4", reading: "万有引力定律的学习，对学生以后学习库仑力和带电粒子在磁场中的运动是一个基础，在高考中属于必考内容，一般以选择题的形式出现，主要考查学生的理解推理能力，所占分值为6分左右。随着我国航天事业的飞速发展，这一部分内容成为热点知识，与现代科学技术的联系非常紧密。",},
            {subject: "专题七：万有引力定律",subjectCombine:"", content: " 万有引力定律及其应用，环绕速度", hour: 2, combine:"", reading: "",},
            {subject: "专题八：经典力学",subjectCombine:"", content: " 第二宇宙速度和第三宇宙速度，经典时空观和相对论时空观", hour: 2, combine:"", reading: "",},
            {subject: "专题九：万有引力与航天章节复习",subjectCombine:"", content: " 复习归纳本章重要知识", hour: 2, combine:"", reading: "",},
            {subject: "专题十：追寻守恒量——能量",subjectCombine:"", content: " 了解守恒思想的重要，建立守恒的观点，知道自然界中能的形式多样性及其转化，易错点：能量转化不是能量消失", hour: 2, combine:"", reading: "能量的概念之所以重要，就是因为它是个守恒量，守恒关系是自然界中十分重要的一类关系",},
            {subject: "专题十一：功",subjectCombine:"", content: " 功的概念和做功的两个要素，理解功的计算公式W=Flcosα，只适用于大小和方向均不变的恒力做功，能进行有关分析和计算，理解正功、负功的物理意义，功是能量转化的量度", hour: 2, combine:"", reading: "公式W=Flcosα中各字母正负取值：F、l均取正值，W的正负取决于cosα的正负，l的确切含义是物体位移的大小，因为高中阶段研究的是质点，物体的位移与“受力作用的质点”的位移是一致的，功与物体的运动状态及运动形式无关",},
            {subject: "专题十二：功率",subjectCombine:"", content: " 理解功率的物理意义，功率的定义及定义式，理解功率与力、速度之间的关系，能运用其解释和计算汽车启动和行驶中的有关问题，区分额定功率和实际功率，区分瞬时功率和平均功率", hour: 2, combine:"", reading: "要注意公式P=Fv中F是恒力时，v是平均速度指平均功率，v是瞬时速度，指瞬时功率；F是变力时，v是瞬时功率，指瞬时功率",},
            {subject: "专题十三：重力势能",subjectCombine:"", content: " 知道重力做功与路径无关，经历重力势能概念的建立过程，理解重力势能及其定义式，知道重力势能的变化和重力做功关系，理解重力势能的相对性", hour: 2, combine:"2", reading: "重力做功和重力势能变化的关系，探究弹性势能表达式的过程是重点，重力做功和重力势能变化的关系，拉力（变力）做功的计算是难点",},
            {subject: "专题十四：探究弹性势能的表达式",subjectCombine:"", content: " 了解弹性势能的概念，知道弹性势能的大小与形变有关，学习并掌握探究弹性势能表达式的基本方法", hour: 2, combine:"", reading: "",},
            {subject: "专题十五：探究功与速度变化的关系",subjectCombine:"", content: " 掌握实验技巧，学会数据处理，弹力做功与速度间的函数关系，实验中没有具体测出橡皮筋对小车做的功，而是设定每一根橡皮筋对小车做功W，来探究小车速度与皮筋做功的关系", hour: 2, combine:"", reading: "实验中应注意解决：相同皮筋的选取及固定，小车运动阻力的平衡，纸带上合适点间距离的测量",},
            {subject: "专题十六：动能和动能定理",subjectCombine:"", content: " 理解动能及其表达式，掌握动能定理及其推导过程，学会用动能定理进行分析、解释和计算生活和生产中的实际问题，体会用能量观点解决力学问题的思路与方法", hour: 2, combine:"", reading: "比较用牛顿定律解题和运用动能解题过程，体会用能量观点解题的优越性",},
            {subject: "专题十七：机械能守恒定律",subjectCombine:"", content: " 功能与势能的相互转化 ，机械能守恒的内容及适用条件，用机械能守恒定律解决力学问题", hour: 2, combine:"", reading: "熟悉机械能守恒定律的推导 ，掌握如何进行系统的选取和定律表达式的选取",},
            {subject: "专题十八：验证机械能守恒定律",subjectCombine:"", content: " 理解实验原理，实验思路和方法，验证机械能守恒定律，掌握能量守恒定律，理解这个定律的重要意义，能用能量守恒定律在分析计算有关能量守恒的综合性问题，理解能量耗散，认清节约能源的重要性 ", hour: 2, combine:"", reading: "注意：实验步骤的操作先后次序 ，数据处理方法的选择，重点：尝试设计验证机械能守恒定律实验方案，经历验证机械能守恒定律的过程，学会对数据进行处理的方法，对能量守恒定律的理解，能量转化和守恒定律的应用",},
            {subject: "专题十九：机械能守恒定律章节复习",subjectCombine:"", content: " 复习归纳本章重要知识", hour: 2, combine:"", reading: "--",},
            {subject: "专题二十：期末复习",subjectCombine:"", content: " 本学期重要知识点梳理和重难点分析", hour: 2, combine:"", reading: "--",},
        ],
        Chemistry:[
            {subject: "氧化还原反应",subjectCombine:"", content: " 氧化还原反应的相关概念、氧化还原反应的配平、氧化还原反应的定量和定性分析、氧化还原反应规", hour: 2, combine:"", reading: "了解氧化还原反应的本质是电子转移；了解常见的氧化还原反应；掌握常见的氧化还原反应的配平和相关计算",},
            {subject: "金属及其化合物1",subjectCombine:"", content: " 金属及其化合物的化学性质、相关盐类的鉴别、化学反应图像的分析、焰色反应、金属冶", hour: 2, combine:"2", reading: "了解常见金属及其重要化合物的主要性质及利用；了解合金的概念及其重要作用；了解常见金属的活泼性顺序",},
            {subject: "金属及其化合物2",subjectCombine:"", content: "", hour: 2, combine:"", reading: "",},
            {subject: "非金属及其化合物1",subjectCombine:"", content: " 硅、氯及其化合物的物化性质、卤素单质的性质及递变规律、卤素离子的检验、置换反应的规", hour: 2, combine:"2", reading: "了解非金属单质及其化合物的重要性质及利用；了解非金属单质及其化合物对环境质量的影响；以新材料、新技术为背景考查非金属单质及其化合物的性质及运用；常见的漂白剂及漂白原理；了解大气污染的来源、危害与治理。联系实际，对化工生产环境保护等常识性了解",},
            {subject: "非金属及其化合物2",subjectCombine:"", content: " 氮、硫及其化合物的性质、相关离子的检验、硫酸硝酸的性质、守恒思想在混合计算中的运用、喷泉实", hour: 2, combine:"", reading: "",},
            {subject: "元素周期律与元素周期律",subjectCombine:"", content: " 元素的递变规律、元素推断、元素周期表和元素周期律的综合运", hour: 2, combine:"", reading: "此部分内容属于高考必考内容，可能是选择题也可能是大题主要考察元素的推导，元素的位置，元素周期律的运用，可能结合物质结构进行现象解释、定性推断等 ",},
            {subject: "化学键",subjectCombine:"", content: " 化学键的类型、电子式的书写、原子结", hour: 2, combine:"", reading: "了解原子构成，元素、核素、同位素的概念，化学键的定义，离子键和共价键的形成以及结构式的表达方法。",},
            {subject: "化学能与热能",subjectCombine:"", content: " 化学键与化学反应中能量变化关系、能量的转化", hour: 2, combine:"3", reading: "这部分的内容和之后选修四的学习有密切关系，要注重基本概念的理解和运用，熟练运用原理解释现象",},
            {subject: "化学能与电能",subjectCombine:"", content: " 化学能与电能的转化、一次电源和二次电源、燃料电池、电极反应方程式的书", hour: 2, combine:"", reading: "",},
            {subject: "化学反应的速率与限度",subjectCombine:"", content: " 化学反应速率、化学反应的限度、化学反应条件的控", hour: 2, combine:"", reading: "",},
            {subject: "甲烷",subjectCombine:"", content: " 有机物的特点和性质、甲烷的分子结构和性质及表示方", hour: 2, combine:"2", reading: "了解甲烷的结构性质和用途，烷烃的性质",},
            {subject: "烷烃",subjectCombine:"", content: " 烷烃的通式、同系物、同分异构体，取代反应与置换反应、复分解反应的比较", hour: 2, combine:"", reading: "",},
            {subject: "来自石油和煤的两种基本化工原料（乙烯、苯）",subjectCombine:"", content: " 乙烯的分子结构和性质、乙烯的实验室制法、鉴别和除去，苯的结构  、性", hour: 2, combine:"", reading: "了解有机化合物中键的特征；了解乙烯、苯等有机物的主要性质；了解乙烯、氯乙烯、苯的衍生物等在化工生产中的重要作用；",},
            {subject: "生活中两种常见的有机物（乙醇、乙酸）",subjectCombine:"", content: " 乙醇、乙酸的分子结构和性质、根、基和官能团的区别，酯化反应实", hour: 2, combine:"", reading: "了解乙醇、乙酸的组成、性质及其重要运用",},
            {subject: "基本营养物（糖类、油脂和蛋白质）",subjectCombine:"", content: " 代表物及化学组成、特征反应、水解反应，鉴别方法及现", hour: 2, combine:"", reading: "了解糖类、油脂、蛋白质和氨基酸的组成结构和性质；了解糖类、油脂和蛋白质对人体健康的重要意义",},
            {subject: "金属冶炼的方法",subjectCombine:"", content: " 金属冶炼的方", hour: 2, combine:"", reading: "金属的冶炼方法",},
            {subject: "海水资源的开发利用",subjectCombine:"", content: " 物质分离的几种方法：海水的食盐提纯、海带中碘的提取；海水中溴的提取；氯碱工业", hour: 2, combine:"2", reading: "了解煤、石油和天然气等综合运用的意义；了解海水的综合利用，了解化学科学发展对自然资源利用的作用；了解金属材料的特点及相关的生产原理",},
            {subject: "资源综合利用 环境保护",subjectCombine:"", content: " 煤的干馏，石油的分馏、裂化和裂解，利用煤、石油、天然气进行合成材料，环境保护、绿色化学（原子经济", hour: 2, combine:"", reading: "",},
        ]
    },
    senior_t: {
        Chinese: [
            {subject: "专题一：戏剧阅读",subjectCombine:"", content: " 《雷雨》课文解读、戏剧文体知识及阅读", hour: 2, combine:"999", reading: "本阶段课程计划安排40课时，课程内容紧扣高二下册重难点，从教材出发明确单元重点，同时在此基础上进行延伸拓展，侧重知识点及答题方法和技巧的梳理。建议学生在学习过程中如有问题及时提出，具体教学时可根据学生掌握情况适当调整。",},
            {subject: "专题二：小说阅读",subjectCombine:"", content: " 小说文体知识、小说主题、人物、情节、景物描写等", hour: 6, combine:"", reading: "",},
            {subject: "专题三：诗词鉴赏1",subjectCombine:"", content: " 诗歌体裁常识、宋词发展、诗歌鉴赏常见考点题型", hour: 2, combine:"", reading: "",},
            {subject: "专题四：诗词鉴赏2",subjectCombine:"", content: " 怀古诗词鉴赏专题、《苏轼词两首》《辛弃疾词两首》", hour: 4, combine:"", reading: "",},
            {subject: "专题五：写作1",subjectCombine:"", content: " 材料作文的分类及观点提取", hour: 2, combine:"", reading: "",},
            {subject: "专题六：写作2",subjectCombine:"", content: " 材料作文的素材选取", hour: 2, combine:"", reading: "",},
            {subject: "专题七：期中复习",subjectCombine:"", content: " 课内重点课文、字音字形、古诗文", hour: 2, combine:"", reading: "",},
            {subject: "专题八：散文阅读1",subjectCombine:"", content: " 散文文体知识、散文主旨、句子赏析", hour: 2, combine:"", reading: "",},
            {subject: "专题九：散文阅读2",subjectCombine:"", content: " 人生哲理散文阅读赏析", hour: 4, combine:"", reading: "",},
            {subject: "专题十：语言文字应用",subjectCombine:"", content: " 词语、病句、句式、语言表达", hour: 2, combine:"", reading: "",},
            {subject: "专题十一：文言文巩固",subjectCombine:"", content: " 《廉颇蔺相如传》《苏武传》重点实词虚词、特殊句式", hour: 2, combine:"", reading: "",},
            {subject: "专题十二：文言文阅读",subjectCombine:"", content: " 人物传记类文言文阅读、作家素材积累、实词虚词积累", hour: 4, combine:"", reading: "",},
            {subject: "专题十三：写作",subjectCombine:"", content: " 如何写议论文、辩证分析", hour: 2, combine:"", reading: "",},
            {subject: "专题十四：名著导读",subjectCombine:"", content: " 莎士比亚戏剧、《谈美》名著导读", hour: 2, combine:"", reading: "",},
            {subject: "专题十五：期末复习",subjectCombine:"", content: " 课内重点课文、字音字形、古诗文、阅读、写作", hour: 2, combine:"", reading: "",},
        ],
        math: [
            {subject: "专题一：导数及其应用",subjectCombine:"6", content: " 导数的概念与几何意义", hour: 2, combine:"999", reading: "本阶段课程计划安排40课时，巩固和拓展导数、推理证明、计数原理、分布列、极坐标、参数方程的基本知识，总结和归纳相应的考试题型，提高导数模块的综合能力，构建函数与导数知识体系，减轻高三复习压力。建议学生在学习过程中如有问题及时提出，具体教学时可根据学生掌握情况适当调整。",},
            {subject: "",subjectCombine:"", content: " 导数的运算", hour: 2, combine:"", reading: "",},
            {subject: "",subjectCombine:"", content: " 利用导数分析函数的单调性、极值、最值", hour: 2, combine:"", reading: "",},
            {subject: "",subjectCombine:"", content: " 导数的分类讨论", hour: 2, combine:"", reading: "",},
            {subject: "",subjectCombine:"", content: " 利用导数证明不等式、零点问题", hour: 2, combine:"", reading: "",},
            {subject: "",subjectCombine:"", content: " 微积分与定积分的应用", hour: 2, combine:"", reading: "",},
            {subject: "专题二：数系的扩充和复数的引入、推理与证明",subjectCombine:"4", content: " 复数考点总结", hour: 2, combine:"", reading: "",},
            {subject: "",subjectCombine:"", content: " 合情推理与演绎推论", hour: 2, combine:"", reading: "",},
            {subject: "",subjectCombine:"", content: " 直接证明与间接证明", hour: 2, combine:"", reading: "",},
            {subject: "",subjectCombine:"", content: " 数学归纳法", hour: 2, combine:"", reading: "",},
            {subject: "期中复习",subjectCombine:"", content: " 根据模考卷情况，进行查漏补缺", hour: 2, combine:"", reading: "",},
            {subject: "专题四：计数原理",subjectCombine:"3", content: " 加法原理、乘法原理、分类分布综合", hour: 2, combine:"", reading: "",},
            {subject: "",subjectCombine:"", content: " 排列组合", hour: 2, combine:"", reading: "",},
            {subject: "",subjectCombine:"", content: " 二项式定理及其应用", hour: 2, combine:"", reading: "",},
            {subject: "专题五：随机变量及其分布",subjectCombine:"2", content: " 离散型随机变量的分布列", hour: 2, combine:"", reading: "",},
            {subject: "",subjectCombine:"", content: " 分布列的期望、方差、正态分布", hour: 2, combine:"", reading: "",},
            {subject: "专题六：坐标系与参数方程",subjectCombine:"3", content: " 极坐标概念与考法汇总", hour: 2, combine:"", reading: "",},
            {subject: "",subjectCombine:"", content: " 参数方程常见形式", hour: 2, combine:"", reading: "",},
            {subject: "",subjectCombine:"", content: " 参数方程在解析几何中的应用", hour: 2, combine:"", reading: "",},
            {subject: "期末复习",subjectCombine:"", content: " 根据模考卷情况，进行查漏补缺", hour: 2, combine:"", reading: "",},
        ],
        English: [
            {subject: "专题一：",subjectCombine:"", content: " Unit 1 Living well", hour: 2, combine:"", reading: "重点单词、短语、句型、重要语法知识点梳理，课文长难句子分析及相关练习与检测",},
            {subject: "专题二：",subjectCombine:"", content: " Unit 2 Healthy eating", hour: 2, combine:"", reading: "重点单词、短语、句型、重要语法知识点梳理，课文长难句子分析及相关练习与检",},
            {subject: "专题三：",subjectCombine:"", content: " Unit 3 Under the sea", hour: 2, combine:"", reading: "重点单词、短语、句型、重要语法知识点梳理，课文长难句子分析及相关练习与检测",},
            {subject: "专题四：",subjectCombine:"", content: " Unit 4 Sharing", hour: 2, combine:"", reading: "重点单词、短语、句型、重要语法知识点梳理，课文长难句子分析及相关练习与检测",},
            {subject: "专题五：",subjectCombine:"", content: " Unit 5 Traveling abroad", hour: 2, combine:"", reading: "重点单词、短语、句型、重要语法知识点梳理，课文长难句子分析及相关练习与检测",},
            {subject: "专题六：",subjectCombine:"", content: " Unit 1 A land of diversity", hour: 2, combine:"", reading: "重点单词、短语、句型、重要语法知识点梳理，课文长难句子分析及相关练习与检测",},
            {subject: "专题七：",subjectCombine:"", content: " Unit2 Cloning", hour: 2, combine:"", reading: "重点单词、短语、句型、重要语法知识点梳理，课文长难句子分析及相关练习与检测",},
            {subject: "专题八：",subjectCombine:"", content: " Unit 3 Investors and inventions", hour: 2, combine:"", reading: "重点单词、短语、句型、重要语法知识点梳理，课文长难句子分析及相关练习与检测",},
            {subject: "专题九：",subjectCombine:"", content: " Unit 4 Pygmalion", hour: 2, combine:"", reading: "重点单词、短语、句型、重要语法知识点梳理，课文长难句子分析及相关练习与检测",},
            {subject: "专题十：",subjectCombine:"", content: " Unit 5 Meeting your ancestors", hour: 2, combine:"", reading: "重点单词、短语、句型、重要语法知识点梳理，课文长难句子分析及相关练习与检测",},
            {subject: "专题十一：",subjectCombine:"", content: " 定语从句", hour: 4, combine:"", reading: "定语从句是学习英语语言的关键，也是高中阶段甚至大学阶段考试的一个常考点、易错点，学生应该理清关系，分类练习杂的用法还没有掌握；另外对need, ought to, dare等用法不了解",},
            {subject: "专题十二：主谓一致",subjectCombine:"", content: " 状语从句", hour: 4, combine:"", reading: "高考考点之一，可以有针对性的做一些练习，多总结易错题目",},
            {subject: "专题十四：虚拟语气",subjectCombine:"", content: " 虚拟语气", hour: 4, combine:"", reading: "对一般现在时的虚拟语气掌握得还不错，对涉及到其他时态如一般过去时、将来时等时态时，容易混淆",},
            {subject: "专题十五：完形填空专项讲解",subjectCombine:"", content: " 完形填空", hour: 2, combine:"", reading: "讲解完形填空题解题技巧以及练习题讲解",},
            {subject: "专题十六： 阅读专项讲解",subjectCombine:"", content: " 阅读", hour: 2, combine:"", reading: "讲解阅读题解题技巧以及练习题讲解",},
            {subject: "专题十七：语法填空",subjectCombine:"", content: " 语法填空", hour: 2, combine:"", reading: "讲解语法填空题解题技巧以及练习题讲解",},
            {subject: "专题十一： 写作专项讲解",subjectCombine:"", content: " 写作", hour: 2, combine:"", reading: "讲解写作技巧以及练笔讲解",},
        ],
        Physics:[
            {subject: "专题一：交变电流 描述交变电流的物理量",subjectCombine:"", content: " 交变电流的产生和变化规律，周期、频率，峰值，有效值，相位", hour: 2, combine:"4", reading: "区别交变电流的瞬时值、峰值、有效值和平均值的使用方法，变压器的动态变化分析和电能输送中的能量守恒是本章重难点，通过这一章的学习使学生了解到，不仅有恒定电流，还有大小和方向都发生变化的交变电流，交变电流与恒定电流有相似的地方，也有自己特殊的规律",},
            {subject: "专题二：电感和电容对交变电流的影响",subjectCombine:"", content: " 电感器和电容器对交变电流的阻碍作用", hour: 2, combine:"", reading: "",},
            {subject: "专题三：变压器，电能的输送",subjectCombine:"", content: " 变压器的原理，理想变压器，电压与匝数的关系，降低输电损耗的两个途径", hour: 2, combine:"", reading: "",},
            {subject: "专题四：章节复习",subjectCombine:"", content: " 复习归纳本章重要知识", hour: 2, combine:"", reading: "",},
            {subject: "专题五：动量和动量定理",subjectCombine:"", content: " 探究碰撞中的不变量，动量，动量定理", hour: 3, combine:"4", reading: "动量守恒定律章节侧重考查动量、动量守恒定律的应用，学习时要注重动量的表达式、动量守恒定律的适用范围，并能用动量守恒定律解释相关物理现象",},
            {subject: "专题六：动量守恒定律",subjectCombine:"", content: " 系统，内力和外力，动量守恒定律及其应用", hour: 3, combine:"", reading: "",},
            {subject: "专题七：碰撞 反冲运动",subjectCombine:"", content: " 弹性碰撞和非弹性碰撞，对心碰撞和非对心碰撞，反冲，火箭", hour: 2, combine:"", reading: "",},
            {subject: "专题八： 章节复习",subjectCombine:"", content: " 复习归纳本章重要知识", hour: 2, combine:"", reading: "",},
            {subject: "专题九：波粒二象性",subjectCombine:"", content: " 光电效应，康普顿效应，爱因斯坦光电效应方程", hour: 2, combine:"4", reading: "波粒二象性、原子结构、原子核这三章的内容在高考中所占比重并不是很大，属于近代物理学领域，从知识上看，涉及到的内容非常广泛，学生以往生活体验较少，一些问题理解起来有一定的难度，从应用上看，可以说与当代高、精、尖科技领域都有着密切的联系",},
            {subject: "专题十：原子结构",subjectCombine:"", content: " 氢原子光谱，氢原子的能级结构、能级公式", hour: 2, combine:"", reading: "",},
            {subject: "专题十一：原子核",subjectCombine:"", content: " 原子核的组成、放射性、原子核的衰变、半衰期，放射性同位素，核力、核反应方程，结合能、质量亏损，裂变反应和聚变反应、裂变反应堆，射线的危害和防护", hour: 4, combine:"", reading: "",},
            {subject: "专题十二：选修3-5复习",subjectCombine:"", content: " 复习归纳本书重要知识", hour: 2, combine:"", reading: "",},
            {subject: "专题十三：分子动理论与统计观点",subjectCombine:"", content: " 分子动理论的基本观点和实验依据，阿伏加德罗常数，气体分子运动速率的统计分布，温度、内能", hour: 2, combine:"3", reading: "选修3-3的概念繁多，规律繁多，要求学生能正确理解，培养学生的理解能力、综合分析问题的能力，培养学生运用数学处理物理问题的能力和良好的计算能力，良好的思维能力和空间想象能力，利用图象分析问题和识图的能力",},
            {subject: "专题十四： 固体、液体与气体",subjectCombine:"", content: " 固体的微观结构，晶体和非晶体，液晶的微观结构，液体的表面张力现象，气体实验定律，理想气体，饱和蒸气、未饱和蒸气，饱和蒸气压，相对湿度", hour: 4, combine:"", reading: "",},
            {subject: "专题十五：热力学定律与能量守恒 ",subjectCombine:"", content: " 热力学第一定律，能量守恒定律，热力学第二定律", hour: 2, combine:"", reading: "",},
            {subject: "专题十六：期末复习",subjectCombine:"", content: " 本学期重要知识点梳理和重难点分析", hour: 4, combine:"", reading: "--",},
        ],
        Chemistry:[
            {subject: "认识有机化合物1",subjectCombine:"", content: " 有机物的分类、结构特点 ", hour: 2, combine:"999", reading: "本阶段课程计划安排了选修5和选修3两部分类容，巩固和拓展有机物和物质结构的基本知识，总结和归纳相应的考试题型，两部分类容可以根学校要求选择其中部分章节学习，减轻高三复习压力。建议学生在学习过程中如有问题及时提出，具体教学时可根据学生掌握情况适当调整。",},
            {subject: "认识有机化合物2",subjectCombine:"", content: " 有机物的命名、研究有机物的一般步骤和方法", hour: 2, combine:"", reading: "",},
            {subject: "脂肪烃",subjectCombine:"", content: " 烷烃、烯烃、炔烃，脂肪烃的来源及其运用", hour: 2, combine:"", reading: "",},
            {subject: "芳香烃",subjectCombine:"", content: " 苯及苯的同系物", hour: 2, combine:"", reading: "",},
            {subject: "卤代烃",subjectCombine:"", content: " 卤代烃的化学性质、卤代烃中卤素的检验", hour: 2, combine:"", reading: "",},
            {subject: "醇和酚",subjectCombine:"", content: " 醇和酚的化学性质与实例、酚类化合物与Br2、H2、NaOH时最大用量的计算", hour: 2, combine:"", reading: "",},
            {subject: "醛和酮",subjectCombine:"", content: " 醛、酮的结构、性质与检验，有机反应的类型总结", hour: 2, combine:"", reading: "",},
            {subject: "羧酸和酯",subjectCombine:"", content: " 羧酸的结构与性质、酯化反应的类型与规律、氢原子活性比较", hour: 2, combine:"", reading: "",},
            {subject: "同系物与同分异构体",subjectCombine:"", content: " 同系物的概念、判断同分异构体数目的方法", hour: 2, combine:"", reading: "",},
            {subject: "有机反应类型1",subjectCombine:"", content: " 取代、加成、消去反应、酯化、", hour: 2, combine:"", reading: "",},
            {subject: "有机反应类型2",subjectCombine:"", content: " 水解、加聚反应、缩聚、氧化、还原反应", hour: 2, combine:"", reading: "",},
            {subject: "有机合成与推断1",subjectCombine:"", content: " 官能团引入、碳骨架的增减、官能团的消除、官能团间的衍变", hour: 2, combine:"", reading: "",},
            {subject: "有机合成与推断2",subjectCombine:"", content: " 有机推断解题模式、常用方法：正推法、逆推法、正逆综合法、解题思路归纳总结", hour: 2, combine:"", reading: "",},
            {subject: "生命中的基础有机化学物质",subjectCombine:"", content: " 油脂、糖类、蛋白质和核酸", hour: 2, combine:"", reading: "",},
            {subject: "高分子化合物",subjectCombine:"", content: " 合成高分子化合物的基本方法、功能高分子材料", hour: 2, combine:"", reading: "",},
            {subject: "原子结构与性质1",subjectCombine:"", content: " 能层与能级、构造原理与能量最低原理、电子云与原子轨道、 ", hour: 2, combine:"", reading: "",},
            {subject: "原子结构与性质2",subjectCombine:"", content: " 电离能、电负性、原子结构和元素性质", hour: 2, combine:"", reading: "",},
        ]
    },
    senior_th: {
        Chinese: [
            {subject: "语言文字运用",subjectCombine:"6", content: " 专题一：正确使用词语（包括成语和熟语）", hour: 2, combine:"999", reading: "本阶段课程计划安排40课时，课程内容主要是根据考纲要求，进行各模块知识点的系统复习。同时，侧重答题方法和技巧的梳理，通过真题模拟练习加深学生对知识的理解。建议学生在学习过程中如有问题及时提出，具体教学时可根据学生掌握情况适当调整。",},
            {subject: "",subjectCombine:"", content: " 专题二：辨析并修改病句", hour: 2, combine:"", reading: "",},
            {subject: "",subjectCombine:"", content: " 专题三：选用、仿用、变化句式", hour: 2, combine:"", reading: "",},
            {subject: "",subjectCombine:"", content: " 专题四：修辞", hour: 2, combine:"", reading: "",},
            {subject: "",subjectCombine:"", content: " 专题五：语言表达简明、连贯得体", hour: 2, combine:"", reading: "",},
            {subject: "",subjectCombine:"", content: " 专题六：正确使用标点符号", hour: 2, combine:"", reading: "",},
            {subject: "古诗文",subjectCombine:"3", content: " 专题七：古诗词鉴赏", hour: 2, combine:"", reading: "",},
            {subject: "",subjectCombine:"", content: " 专题八：文言文阅读一（实词、虚词、文言句式）", hour: 2, combine:"", reading: "",},
            {subject: "",subjectCombine:"", content: " 专题九：文言文阅读二（归纳要点、概括中心）", hour: 2, combine:"", reading: "",},
            {subject: "文学类文本阅读",subjectCombine:"3", content: " 专题十：文学类文本阅读（小说）", hour: 2, combine:"", reading: "",},
            {subject: "",subjectCombine:"", content: " 专题十一：文学类文本阅读（散文）", hour: 4, combine:"", reading: "",},
            {subject: "",subjectCombine:"", content: " 专题十二：文学类文本阅读（诗歌、戏剧）", hour: 4, combine:"", reading: "",},
            {subject: "论述类文本阅读",subjectCombine:"", content: " 专题十三：论述类文本阅读", hour: 4, combine:"", reading: "",},
            {subject: "实用类文本阅读",subjectCombine:"3", content: " 专题十四：实用类文本阅读（新闻）", hour: 2, combine:"", reading: "",},
            {subject: "",subjectCombine:"", content: " 专题十五：实用类文本阅读（传记）", hour: 2, combine:"", reading: "",},
            {subject: "",subjectCombine:"", content: " 专题十六：实用类文本阅读（科普）", hour: 2, combine:"", reading: "",},
            {subject: "写作",subjectCombine:"2", content: " 专题十七：材料作文", hour: 2, combine:"", reading: "",},
            {subject: "",subjectCombine:"", content: " 专题十八：命题/话题作文", hour: 2, combine:"", reading: "",},
            {subject: "考前冲刺",subjectCombine:"2", content: " 专题十九：考前答疑及冲刺一", hour: 2, combine:"", reading: "",},
            {subject: "",subjectCombine:"", content: " 专题二十：考前答疑及冲刺二", hour: 2, combine:"", reading: "",},
        ],
        math: [
            {subject: "专题一：函数与方程思想",subjectCombine:"", content: " 函数是中学数学的一个重要概念，它渗透在数学的各部分内容中，一直是高考的热点、重点内容。函数的思想，就是用运动变化的观点，分析和研究具体问题中的数量关系，建立函数关系，运用函数的知识，使问题得到解决。", hour: 2, combine:"3", reading: "数学思想是高考数学重要内容，在高考解题中占有非常重要的地位。熟练掌握数学思想，可以快速准确的分析并解决数学相关问题。",},
            {subject: "专题二：数形结合思想",subjectCombine:"", content: " 通过数和形之间的对应关系和相互转化来解决问题的思想方法。", hour: 2, combine:"", reading: "",},
            {subject: "专题三：分类讨论思想",subjectCombine:"", content: " 当问题所给的对象不能进行统一研究时，就需要对研究对象按某个标准进行分类，然后对每一类分别研究得出每一类的结论，最后综合各类结果得到整个问题的解答。", hour: 2, combine:"", reading: "",},
            {subject: "专题四：化归与转化思想",subjectCombine:"", content: " 将待解决的问题，通过某种转化过程，归结为一个已经解决或者比较容易解决的问题，然后通过乙问题的解答返回去求得原问题甲的解答。", hour: 2, combine:"7", reading: "精选各大高考重要板块的中档题和压轴题，让学生考前适当训练并听讲，让学生保持积极思考的状态。",},
            {subject: "专题五：函数与导数培优",subjectCombine:"", content: " 精选函数与导数的中档题和压轴题", hour: 4, combine:"", reading: "",},
            {subject: "专题六：三角与向量培优",subjectCombine:"", content: " 精选三角与向量的中档题和压轴题", hour: 4, combine:"", reading: "",},
            {subject: "专题七：立体几何培优",subjectCombine:"", content: " 精选立体几何的中档题和压轴题", hour: 4, combine:"", reading: "",},
            {subject: "专题八：数列培优",subjectCombine:"", content: " 精选数列的中档题和压轴题", hour: 4, combine:"", reading: "",},
            {subject: "专题九：解析几何培优",subjectCombine:"", content: " 精选解析几何的中档题和压轴题", hour: 4, combine:"", reading: "",},
            {subject: "专题十：统计概率培优",subjectCombine:"", content: " 精选统计概率的中档题和压轴题", hour: 2, combine:"", reading: "",},
            {subject: "专题十一：高考冲刺模拟一",subjectCombine:"", content: " 检测基础知识哪里有漏洞，定时定点做考试训练", hour: 2, combine:"5", reading: "冲刺和押题卷不会太难，为学生考前练手准备，最后冲刺的几周调整心态比学习较难的知识更重要。",},
            {subject: "专题十二：高考冲刺模拟二",subjectCombine:"", content: " 检查基础知识哪里有漏洞，定时定点做考试训练", hour: 2, combine:"", reading: "",},
            {subject: "专题十三：知识点查漏补缺",subjectCombine:"", content: " 根据模考卷情况，进行查漏补缺", hour: 2, combine:"", reading: "",},
            {subject: "专题十四：高考押题卷一",subjectCombine:"", content: " 教研根据高考考纲和历年出题规律，提炼高考押题卷", hour: 2, combine:"", reading: "",},
            {subject: "专题十五：高考押题卷二",subjectCombine:"", content: " 教研根据高考考纲和历年出题规律，提炼高考押题卷", hour: 2, combine:"", reading: "",},
        ],
        English: [
            {subject: "专题一：",subjectCombine:"", content: " 动词的时态和语态", hour: 4, combine:"999", reading: "把高中主要语法点以专题的形式进行系统的讲解，并配合相应的习题进行巩固训练。",},
            {subject: "专题二：",subjectCombine:"", content: " 非谓语动词", hour: 4, combine:"", reading: "",},
            {subject: "专题三：",subjectCombine:"", content: " 动词与动词词组", hour: 4, combine:"", reading: "",},
            {subject: "专题四：",subjectCombine:"", content: " 情态动词", hour: 4, combine:"", reading: "",},
            {subject: "专题五：",subjectCombine:"", content: " 虚拟语气", hour: 4, combine:"", reading: "",},
            {subject: "专题六：",subjectCombine:"", content: " 状语从句", hour: 4, combine:"", reading: "",},
            {subject: "专题七：",subjectCombine:"", content: " 定语从句", hour: 4, combine:"", reading: "",},
            {subject: "专题八：",subjectCombine:"", content: " 名词性从句", hour: 4, combine:"", reading: "",},
            {subject: "专题九：",subjectCombine:"", content: " 语法总结", hour: 4, combine:"", reading: "",},
            {subject: "专题十：",subjectCombine:"", content: " 阅读", hour: 4, combine:"", reading: "",},
            {subject: "专题十一：",subjectCombine:"", content: " 完形填空", hour: 4, combine:"", reading: "",},
            {subject: "专题十二：",subjectCombine:"", content: " 语法填空", hour: 4, combine:"", reading: "",},
            {subject: "专题十三：",subjectCombine:"", content: " 写作练习", hour: 4, combine:"", reading: "",},
        ],
        Physics:[
            {subject: "专题一：一模复习1",subjectCombine:"", content: " 选择题复习训练", hour: 2, combine:"4", reading: "根据学生情况调整上课的内容和课时，可以精选历年一模试卷上的中档题和压轴题，一般2月底3月初会进行一模考试。",},
            {subject: "专题二：一模复习2",subjectCombine:"", content: " 实验题复习", hour: 2, combine:"", reading: "",},
            {subject: "专题三：一模复习3",subjectCombine:"", content: " 解答题复习", hour: 4, combine:"", reading: "",},
            {subject: "专题四： 一模考前复习",subjectCombine:"", content: " 一模考前定时定量模拟训练", hour: 2, combine:"", reading: "",},
            {subject: "专题五： 力学模块专题",subjectCombine:"", content: " 力学模块综合复习训练", hour: 6, combine:"4", reading: "精选各模块和历年二模试卷上的的经典题目，让学生考前适当训练并听讲，训练学生保持积极思考的状态和良好的心态，一般3月和4月二轮复习，分模块综合的复习",},
            {subject: "专题六：电磁学模块专题",subjectCombine:"", content: " 电磁学模块综合复习训练", hour: 6, combine:"", reading: "",},
            {subject: "专题七：热学模块专题",subjectCombine:"", content: " 热学模块综合复习训练", hour: 2, combine:"", reading: "",},
            {subject: "专题八：光学模块专题",subjectCombine:"", content: " 光学模块综合复习训练", hour: 2, combine:"", reading: "",},
            {subject: "专题九：知识点查漏补缺",subjectCombine:"", content: " 根据二模考卷结果情况，进行查漏补缺", hour: 4, combine:"3", reading: "5月前后开始三轮，迎接高考，学生考前准备，不需要太难的题，可以训练一下重要的方法和技巧，最后冲刺的几周调整心态比学习较难的知识更重要",},
            {subject: "专题十：三模考前复习模拟",subjectCombine:"", content: " 三模冲刺，综合训练", hour: 4, combine:"", reading: "",},
            {subject: "专题十一：高考冲刺模拟",subjectCombine:"", content: " 查漏补缺，回归基础，综合训练，调整心态", hour: 6, combine:"", reading: "",},
        ],
        Chemistry:[
            {subject: "化学基本概念1",subjectCombine:"", content: " 物质的量、气体摩尔体积、物质的量浓度、一定物质的量浓度溶液的配制", hour: 2, combine:"9", reading: "这部分内容一定要熟记概念，抓住理解的要点，了解本质原因，深挖题目陷阱，作为高考的必考点我们要确保这部分内容不会出错，相对来说这部分内容相对简单。<br>根据物质的物化性质推测物质名称，了解物质的用途，根据图像做出准确判断，这部分主要以选择题和实验题出现会和选修四合起来综合考察学生逻辑思维能力和综合分析能力。",},
            {subject: "化学基本概念2",subjectCombine:"", content: " 物质的组成、分类与分散系，胶体的特性、化学用语", hour: 2, combine:"", reading: "",},
            {subject: "化学基本概念3",subjectCombine:"", content: " 离子共存、离子方程式书写、离子反应与检验", hour: 2, combine:"", reading: "",},
            {subject: "化学基本概念4",subjectCombine:"", content: " 氧化还原反应", hour: 2, combine:"", reading: "",},
            {subject: "元素及其化合物1",subjectCombine:"", content: " 金属单质及其化合物", hour: 2, combine:"", reading: "",},
            {subject: "元素及其化合物2",subjectCombine:"", content: " 非金属单质及其化合物", hour: 2, combine:"", reading: "",},
            {subject: "元素及其化合物3",subjectCombine:"", content: " 无机化合物综合推断", hour: 2, combine:"", reading: "",},
            {subject: "元素及其化合物4",subjectCombine:"", content: " 无机化工生产流程分析", hour: 2, combine:"", reading: "",},
            {subject: "元素周期表与周期律",subjectCombine:"", content: " 原子结构、化学键与物质类别、元素周期表的结构及应用、元素周期律及其应用", hour: 2, combine:"", reading: "",},
            {subject: "化学能与热能",subjectCombine:"", content: " 化学反应中的能量变化、反应热、燃烧热、中和热、热化学方程式的书写、盖斯定律及其反应热的简单计算", hour: 2, combine:"3", reading: "熟练掌握能量转化关系，做好定量定性分析，熟练掌握概念，灵活运用。这部分主要以选择题出现，内容较难。需要学生能做出科学分析。",},
            {subject: "化学能与电能1",subjectCombine:"", content: " 原电池工作原理及应用、电极反应方程式的书写", hour: 2, combine:"", reading: "",},
            {subject: "化学能与电能2",subjectCombine:"", content: " 电解池工作原理及应用、金属的腐蚀与防护", hour: 2, combine:"", reading: "",},
            {subject: "化学反应速率与化学平衡1",subjectCombine:"", content: " 化学反应速率及其影响因素", hour: 2, combine:"3", reading: "主要考查对概念的理解，外界因素对化学反应速率的影响以及利用图形图像做相关的简单计算。",},
            {subject: "化学反应速率与化学平衡2",subjectCombine:"", content: " 化学平衡及其影响因素、等效平衡", hour: 2, combine:"", reading: "",},
            {subject: "化学反应速率与化学平衡3",subjectCombine:"", content: " 化学平衡常数、转化率的含义及计算、综合运用", hour: 2, combine:"", reading: "",},
            {subject: "电解质溶液1",subjectCombine:"", content: " 电解质的概念、弱电解质电离、水的电离与溶液pH计算", hour: 2, combine:"6", reading: "这部分题型主要以选择题为主，以考察外界条件对弱电解质电离平衡的影响为主，会将电离平衡常数、水的离子积等相关知识综合考查。<br>高考会以一道选择题和一道有机综合题出现，主要考查烃以及烃类衍生物性质及检验。",},
            {subject: "电解质溶液2",subjectCombine:"", content: " 盐类水解、离子浓度大小比较", hour: 2, combine:"", reading: "",},
            {subject: "电解质溶液3",subjectCombine:"", content: " 沉淀溶解平衡及其移动、酸碱中和滴定", hour: 2, combine:"", reading: "",},
            {subject: "常见的有机化合物1",subjectCombine:"", content: " 烃类物质的结构、性质，烃的衍生物的结构、性质", hour: 2, combine:"", reading: "",},
            {subject: "常见的有机化合物2",subjectCombine:"", content: " 有机物的结构与同分异构体现象、有机反应类型", hour: 2, combine:"", reading: "",},
            {subject: "常见的有机化合物3",subjectCombine:"", content: " 基本营养物质和有机合成材料、有机合成与推断", hour: 2, combine:"", reading: "",},
            {subject: "化学实验1",subjectCombine:"", content: " 常用仪器使用、基本操作，物质的制备与性质实验、物质的分离、提纯；物质的检验与鉴别", hour: 2, combine:"", reading: "根据实验选择正确的仪器、试剂，根据实验原理做出合理的解释，并根据实验分离、提纯、鉴别某些物质，对实验方案做出合理的评价并设计实验",},
            {subject: "化学实验2",subjectCombine:"", content: " 重要的定量实验、实验方案的设计与评价", hour: 2, combine:"", reading: "--",},
        ]
    },
}
var spring1 = {
    Chinese: [
        {subject: "专题一：标题的含义和作用",subjectCombine:"", content: "《爸爸的花儿落了》课文内容理解、标题的含义和作用", hour: 2, combine:9999, reading: "本阶段课程计划安排40课时，课程内容紧扣初一下册重难点，从教材出发明确单元重点，同时在此基础上进行延伸拓展，侧重知识点及答题方法和技巧的梳理。建议学生在学习过程中如有问题及时提出，具体教学可根据学生掌握情况适当调整。",},
        {subject: "专题二： 现代诗歌理解",subjectCombine:"", content: "《诗两首》、诗歌的主题、象征的含义", hour: 2, combine:"", reading: "",},
        {subject: "专题三： 文言文巩固1",subjectCombine:"", content: "《伤仲永》重点实词虚词解释、人物分析、课文主旨", hour: 2, combine:"", reading: "",},
        {subject: "专题四：写作和口语交际",subjectCombine:"", content: "写作作文方法指导：叙事要完整", hour: 2, combine:"", reading: "",},
        {subject: "专题五： 揣摩精彩词句段落",subjectCombine:"", content: "《黄河颂》课文内容理解、修辞方法的作用", hour: 2, combine:"", reading: "",},
        {subject: "专题六：文言文巩固2",subjectCombine:"", content: "《木兰诗》重点实词虚词解释、课文解析及阅读拓展", hour: 2, combine:"", reading: "",},
        {subject: "专题七：评价人物形象，学习人物精神",subjectCombine:"", content: "《邓稼先》《闻一多先生的说和做》课文主旨、人物分析", hour: 2, combine:"", reading: "",},
        {subject: "专题八： 期中复习",subjectCombine:"", content: " 课内重点课文、字音字形、古诗文", hour: 2, combine:"", reading: "",},
        {subject: "专题九： 小说阅读",subjectCombine:"", content: " 《社戏》课文内容理解、小说文体知识及阅读", hour: 2, combine:"", reading: "",},
        {subject: "专题十：文言文巩固3",subjectCombine:"", content: "《口技》重点实词虚词解释、课文解析及文言文阅读拓展", hour: 2, combine:"", reading: "",},
        {subject: "专题十一：写作",subjectCombine:"", content: "写人作文方法指导：写人要抓住特点", hour: 2, combine:"", reading: "",},
        {subject: "专题十二： 理解课文主旨",subjectCombine:"", content: "《伟大的悲剧》《在沙漠中心》课文主旨理解及阅读拓展", hour: 2, combine:"", reading: "",},
        {subject: "专题十三： 文言文巩固4",subjectCombine:"", content: "《狼》重点实词虚词解释、课文解析及文言文阅读拓展", hour: 2, combine:"", reading: "",},
        {subject: "专题十四：现代文阅读理解",subjectCombine:"", content: "标题的含义作用、句子的理解、人物形象的分析", hour: 6, combine:"", reading: "",},
        {subject: "专题十五：写作",subjectCombine:"", content: "描写要生动及习作点评与修改", hour: 2, combine:"", reading: "",},
        {subject: "专题十六：名著导读",subjectCombine:"", content: "《童年》《昆虫记》名著导读", hour: 2, combine:"", reading: "",},
        {subject: "专题十七：期末复习",subjectCombine:"", content: " 课内重点课文、字音字形、古诗文、阅读、写作", hour: 4, combine:"", reading: "",},
    ]
};

$(function () {
    var grade = "middle_o",
        subject;
    $("#springTab li.active a:first-child").css({backgroundColor:"#3AC63A",color:"#FFF"});
    $("#springContent div.active li:first-child a").css({backgroundColor:"#3AC63A",color:"#FFF"});
    // $("table tbody tr").css("backgroundColor","red");
    $("#springTab li").on("click",function () {
        $("#springTab li a").css({backgroundColor:"",color:"#3AC63A"});
        $(this).find("a").css({backgroundColor:"#3AC63A",color:"#FFF"});
        grade = $(this).data("grade");
    })
    $("#springContent li").on("click",function () {
        $("#springContent li a").css({backgroundColor:"",color:"#3AC63A"});
        $(this).find("a").css({backgroundColor:"#3AC63A",color:"#FFF"});
        subject = $(this).data("subject");
        spring1.Chinese = spring[grade][subject];
        // console.log(spring1);
        $("#springAll").html(template("spring", spring1));
    })
    // console.log(spring1);
    // console.log(spring[grade][subject]);
    template.config("escape", false);
    $("#springAll").html(template("spring", spring1));
})
